[project]
name = "msa-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "confluent-kafka>=2.12.2",
    "fastapi>=0.123.7",
    "python-dotenv>=1.2.1",
    "uvicorn>=0.38.0",
]
